# Azure DevOps Pipeline for Docker Build and Deploy to Azure Web App

trigger:
- master

variables:
  azureSubscription: '16edcf4a-91ee-411e-862b-e04fa8aa99a3'  # Replace with your Azure service connection ID
  webAppName: 'receptionist'  # Replace with your Azure Web App name
  acrLoginServer: 'voicerecep.azurecr.io'  # Replace with your ACR login server
  acrRegistry: 'voicerecep'  # Replace with your ACR registry name
  dockerfilePath: '**/Dockerfile'  # Path to Dockerfile in your repo

stages:
- stage: Build
  displayName: Build and Push to ACR
  jobs:
  - job: BuildAndPushJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        containerRegistry: 'ACR Connection'  # Azure Container Registry service connection in Azure DevOps
        repository: $(acrLoginServer)/$(acrRegistry)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy to Azure Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Azure Web App Environment'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              containers: $(acrLoginServer)/$(acrRegistry):$(Build.BuildId)
