# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- azure-pipelines

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '76ff0624-c36c-43dd-bf21-e0f62f4c1ee8'
  imageRepository: 'azdevopsrecep'
  containerRegistry: 'mehboob.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  KEY_VAULT: 'https://voicedbcred.vault.azure.net'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)



    - task: AzureRmWebAppDeployment@5
      inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Azure for Students(8c467071-620f-4d5d-9c84-38c9f928d546)'
            appType: 'webAppContainer'
            WebAppName: 'receptionist'
            DockerNamespace: 'mehboob.azurecr.io'
            DockerRepository: 'azdevopsrecep'
            DockerImageTag: '$(tag)'
            StartupCommand: 'python app.py'